"""assign multiple taxonomies to user

Revision ID: 2a41eeb0046d
Revises: a2121a685105
Create Date: 2025-08-30 09:54:09.207314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a41eeb0046d'
down_revision: Union[str, Sequence[str], None] = 'a2121a685105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('user_taxonomies_one_active_per_user'), table_name='user_taxonomies', postgresql_where='(enabled = true)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('user_taxonomies_one_active_per_user'), 'user_taxonomies', ['user_id'], unique=True, postgresql_where='(enabled = true)')
    # ### end Alembic commands ###
