"""create xbrl_contexts

Revision ID: 650127a0472e
Revises: 2a41eeb0046d
Create Date: 2025-09-08 11:15:37.051501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '650127a0472e'
down_revision: Union[str, Sequence[str], None] = '2a41eeb0046d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xbrl_contexts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('context_id', sa.String(length=128), nullable=False),
    sa.Column('entity_scheme', sa.String(length=512), nullable=False),
    sa.Column('entity_identifier', sa.String(length=128), nullable=False),
    sa.Column('entity_name', sa.String(length=512), nullable=True),
    sa.Column('lei', sa.String(length=20), nullable=True),
    sa.Column('period_type', sa.Enum('instant', 'duration', 'forever', name='xbrl_period_type'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('instant_date', sa.Date(), nullable=True),
    sa.Column('dimensions_json', sa.JSON(), nullable=True),
    sa.Column('taxonomy_id', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('is_default_context', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('valid', 'warning', 'error', name='xbrl_context_status'), nullable=False),
    sa.Column('validation_messages', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("( (period_type = 'instant'  AND instant_date IS NOT NULL AND start_date IS NULL AND end_date IS NULL) OR  (period_type = 'duration' AND start_date IS NOT NULL AND end_date IS NOT NULL                            AND instant_date IS NULL AND end_date >= start_date) OR  (period_type = 'forever'  AND instant_date IS NULL AND start_date IS NULL AND end_date IS NULL))", name='ck_xc_period_fields'),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['taxonomies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xbrl_contexts_content_hash'), 'xbrl_contexts', ['content_hash'], unique=True)
    op.create_index(op.f('ix_xbrl_contexts_context_id'), 'xbrl_contexts', ['context_id'], unique=False)
    op.create_index(op.f('ix_xbrl_contexts_entity_identifier'), 'xbrl_contexts', ['entity_identifier'], unique=False)
    op.create_index(op.f('ix_xbrl_contexts_lei'), 'xbrl_contexts', ['lei'], unique=False)
    op.create_index(op.f('ix_xbrl_contexts_taxonomy_id'), 'xbrl_contexts', ['taxonomy_id'], unique=False)
    op.create_index('ix_xc_entity_period', 'xbrl_contexts', ['entity_identifier', 'period_type', 'start_date', 'end_date', 'instant_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_xc_entity_period', table_name='xbrl_contexts')
    op.drop_index(op.f('ix_xbrl_contexts_taxonomy_id'), table_name='xbrl_contexts')
    op.drop_index(op.f('ix_xbrl_contexts_lei'), table_name='xbrl_contexts')
    op.drop_index(op.f('ix_xbrl_contexts_entity_identifier'), table_name='xbrl_contexts')
    op.drop_index(op.f('ix_xbrl_contexts_context_id'), table_name='xbrl_contexts')
    op.drop_index(op.f('ix_xbrl_contexts_content_hash'), table_name='xbrl_contexts')
    op.drop_table('xbrl_contexts')
    # ### end Alembic commands ###
