"""update contexts

Revision ID: 93f4ef8703b5
Revises: 650127a0472e
Create Date: 2025-09-08 11:36:45.817860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f4ef8703b5'
down_revision: Union[str, Sequence[str], None] = '650127a0472e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xbrl_contexts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_xbrl_contexts_content_hash'), table_name='xbrl_contexts')
    op.create_index(op.f('ix_xbrl_contexts_content_hash'), 'xbrl_contexts', ['content_hash'], unique=False)
    op.create_index(op.f('ix_xbrl_contexts_user_id'), 'xbrl_contexts', ['user_id'], unique=False)
    op.create_unique_constraint('uq_ctx_hash_per_user', 'xbrl_contexts', ['user_id', 'content_hash'])
    op.create_unique_constraint('uq_ctx_id_per_user', 'xbrl_contexts', ['user_id', 'context_id'])
    op.create_foreign_key(None, 'xbrl_contexts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'xbrl_contexts', type_='foreignkey')
    op.drop_constraint('uq_ctx_id_per_user', 'xbrl_contexts', type_='unique')
    op.drop_constraint('uq_ctx_hash_per_user', 'xbrl_contexts', type_='unique')
    op.drop_index(op.f('ix_xbrl_contexts_user_id'), table_name='xbrl_contexts')
    op.drop_index(op.f('ix_xbrl_contexts_content_hash'), table_name='xbrl_contexts')
    op.create_index(op.f('ix_xbrl_contexts_content_hash'), 'xbrl_contexts', ['content_hash'], unique=True)
    op.drop_column('xbrl_contexts', 'user_id')
    # ### end Alembic commands ###
