"""add uniques for user_taxonomies

Revision ID: a2121a685105
Revises: f28769ef4842
Create Date: 2025-08-29 09:38:08.953163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2121a685105'
down_revision: Union[str, Sequence[str], None] = 'f28769ef4842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_taxonomies_one_active_per_user', 'user_taxonomies', ['user_id'], unique=True, postgresql_where=sa.text('enabled = TRUE'))
    op.create_unique_constraint('user_taxonomies_user_taxonomy_uniq', 'user_taxonomies', ['user_id', 'taxonomy_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_taxonomies_user_taxonomy_uniq', 'user_taxonomies', type_='unique')
    op.drop_index('user_taxonomies_one_active_per_user', table_name='user_taxonomies', postgresql_where=sa.text('enabled = TRUE'))
    # ### end Alembic commands ###
