"""add taxonomies and user_taxonomies

Revision ID: c9fd16c6a873
Revises: 1d9c473cce7d
Create Date: 2025-08-28 11:46:32.095319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9fd16c6a873'
down_revision: Union[str, Sequence[str], None] = '1d9c473cce7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
